name: faltool
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.3
  equatable: ^2.0.5
  flutter_image_compress: ^2.0.4
  ansicolor: ^2.0.1
  uuid: ^4.0.0
  path_provider: ^2.1.1
  logger: ^2.0.2
  stack_trace: ^1.11.0
  dartx: ^1.2.0
  rxdart: ^0.27.7
  enum_to_string: ^2.0.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
